services:
  - type: web
    name: esotericai-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_api.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        generateValue: true
    healthCheckPath: /health